### PR TITLE
Adds tutorial on how to track scroll depth

### LINKED ISSUE #15: Add tutorial on how to track scroll height with GTM
For the dwyl-site @finnhodgkin and I have been working on setting up how to track how far a user scrolls on the page. We've used a combination of this tutorial: https://gtm.tips/scroll-tracking-google-google-tag-manager-the-tracking/ and writing our own script as kept track of in https://github.com/dwyl/dwyl-site/issues/222

It makes sense for us to make it so that this process is able to replicated, and adding a tutorial here seems to be the best way to do that!

### PR DESCRIPTION
**Pull request by ZooeyMiller**
I've added a tutorial on tracking scroll depth and time on page with a custom HTML tag in Google Tag Manager.
fix #15

### CODE REVIEW

**Comment by ZooeyMiller** [comment]
hey @Danwhy, asked for a review just because it seems you've written a lot of the stuff in this repo!

**Review by Danwhy — APPROVED** [review]
Looks great, nice work

**Review by iteles — APPROVED** [review]
Excited to have this going in! 🎉 
Can we add a screenshot on what the data will look like in GA?

**Comment by iteles** [comment]
@ZooeyMiller Added issue #19, merging this in.

**Pull request merged**
